name: "Smart Voltronic Node-RED"
version: "1.0.1"
slug: "smart-voltronic"
description: "Node-RED Voltronic plug & play: le flow est mis Ã  jour via MAJ add-on"
arch:
  - aarch64
  - amd64
  - armv7
startup: services
boot: auto
init: false

privileged: true
devices:
  - /dev/ttyUSB0
  - /dev/ttyUSB1
  - /dev/ttyUSB2

ports:
  1880/tcp: 1880

options:
  serial_ports:
    - "/dev/ttyUSB0"
  mqtt_host: "core-mosquitto"
  mqtt_port: 1883
  mqtt_user: ""
  mqtt_pass: ""

schema:
  serial_ports:
    - str
  mqtt_host: str
  mqtt_port: int
  mqtt_user: str
  mqtt_pass: str

panel_icon: mdi:solar-power
