name: "Smart Voltronic Node-RED"
version: "1.3.6"
slug: smart_voltronic
description: "Node-RED Voltronic plug & play: flow mis Ã  jour via MAJ add-on"

arch:
  - aarch64
  - amd64
  - armv7
  - armhf
  - i386

startup: services
boot: auto
init: false
uart: true

ports:
  1892/tcp: 1892

panel_icon: mdi:solar-power

options:
  serial_ports:
    - "/dev/serial/by-id/CHANGE-ME-1"
    - "/dev/serial/by-id/CHANGE-ME-2"
    - "/dev/serial/by-id/CHANGE-ME-3"
  mqtt_host: "core-mosquitto"
  mqtt_port: 1883
  mqtt_user: ""
  mqtt_pass: ""
  send_bip: true   # ðŸ”” NEW OPTION

schema:
  serial_ports:
    - str
    - str?
    - str?
  mqtt_host: str
  mqtt_port: int
  mqtt_user: str
  mqtt_pass: password
  send_bip: bool   # ðŸ”” NEW OPTION
